---

# these are the necessary steps for roll forward

- name: Stop old proxies
  service:
    name: zabbix-proxy
    state: stopped
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['zabbix_proxy_set1']}}"

- name: Stop old java gateways
  service:
    name: zabbix-java-gateway
    state: stopped
  delegate_to: "{{ item }}"
  become: true
  loop: "{{ groups['zabbix_proxy_set1']}}"

- name: Stop old server
  service:
    name: zabbix-server
    state: stopped
  delegate_to: "{{ item }}"
  become: true
  loop: "{{ groups['zabbix_server_set1']}}"

- name: Start new proxies
  service:
    name: zabbix-proxy
    state: started
  delegate_to: "{{ item }}"
  become: true
  loop: "{{ groups['zabbix_proxy_set2']}}"

- name: Start new java gateways
  service:
    name: zabbix-java-gateway
    state: started
  delegate_to: "{{ item }}"
  become: true
  loop: "{{ groups['zabbix_proxy_set2']}}"

- name: Start new server
  service:
    name: zabbix-server
    state: started
  delegate_to: "{{ item }}"
  become: true
  loop: "{{ groups['zabbix_server_set2']}}"

- include_role:
    name: move_agents
  vars:
    new_proxy: "{{ proxy_item }}"
    old_proxy: "{{ proxy_item }}"
    zabbix_apihost: "{{ groups['zabbix_web_set2'][0] }}"
  delegate_to: "{{ proxy_item }}"
  loop: "{{ groups['zabbix_proxy_set2']}}"
  loop_control:
    loop_var: proxy_item
- include_role:
    name: move_agents
  vars:
    new_proxy: "{{ proxy_item }}"
    old_proxy: "{{ hostvars[proxy_item]['failover'] }}"
    zabbix_apihost: "{{ groups['zabbix_web_set2'][0] }}"
  delegate_to: "{{ proxy_item }}"
  loop: "{{ groups['zabbix_proxy_set2']}}"
  loop_control:
    loop_var: proxy_item
